### ISSUE TITLE
Clientside owners don't update after player reconnects / joins to already spawned ents

### ISSUE THREAD

**Issue by adamnejm** [Nebual/NadmodPP#4]
New props - spawned after player already joined are received properly by the clientside,
but props that already were spawned before player connected will display N/A and won't have ownership on client (server's CPPIGetOwner will still return the correct player)

NADMOD.SendPropOwners() works properly (tho client might not receive it since it's instantly called on [PlayerInitialSpawn](https://wiki.garrysmod.com/page/GM/PlayerInitialSpawn)).

From my initial tests client receives only a small chunk of that containing weapons he's spawned with.
Sent IDs: 0-109 (last 10 being my props)
Received IDs: 83-94.
All that with few skipped of course due to IDs being unique.
 
I dislike networking to extend where I'm not even gonna start thinking of what's happening there, sorry @thegrb93 ;c

**Comment by thegrb93** [comment]
Sorry, didn't realize the bug you mentioned was from my update. The networking looks fine. I think the problem is player.GetBySteamID is being called before the players are valid entities.

**Comment by thegrb93** [comment]
Ok it was actually two issues.
